"use client";

import { useEffect, useRef, useState, useTransition } from "react";
import Link from "next/link";
import Papa from "papaparse";
import { bulkCreateListings, type BulkRow, type BulkUploadResult } from "../../actions";
import { listSectors } from "../../sectors/actions";
import type { Sector } from "@/lib/supabase/types";

const REQUIRED_COLUMNS = ["name", "category", "subcategory", "sector", "description"];

export default function BulkUploadPage() {
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [fileName, setFileName] = useState<string | null>(null);
  const [rows, setRows] = useState<BulkRow[]>([]);
  const [parseErrors, setParseErrors] = useState<string[]>([]);
  const [result, setResult] = useState<BulkUploadResult | null>(null);
  const [sectors, setSectors] = useState<Sector[]>([]);
  const [isPending, startTransition] = useTransition();

  // Sectors are managed at /admin/sectors now, not hardcoded — fetched here
  // purely to show the current valid ids in the instructions below.
  useEffect(() => {
    listSectors()
      .then(setSectors)
      .catch(() => {});
  }, []);

  // Accepts the sector column as either the bare number ("6") or the
  // display name ("Sector 6" / "sector 6") — CSVs pasted or generated by
  // hand often use the name, and Number("Sector 6") would otherwise always
  // come out NaN (see the same fix in admin/apartments/ApartmentsManager.tsx).
  function resolveSector(raw: string): number {
    const trimmed = (raw ?? "").trim();
    if (/^\d+$/.test(trimmed)) return Number(trimmed);
    const byName = sectors.find((s) => s.name.toLowerCase() === trimmed.toLowerCase());
    if (byName) return byName.id;
    const digitsMatch = trimmed.match(/\d+/);
    if (digitsMatch) {
      const id = Number(digitsMatch[0]);
      if (sectors.some((s) => s.id === id)) return id;
    }
    return NaN;
  }

  function handleFile(file: File) {
    setFileName(file.name);
    setResult(null);

    Papa.parse<Record<string, string>>(file, {
      header: true,
      skipEmptyLines: true,
      transformHeader: (h) => h.trim(),
      complete: (results) => {
        const errors: string[] = [];
        const headers = results.meta.fields ?? [];
        const missing = REQUIRED_COLUMNS.filter((c) => !headers.includes(c));
        if (missing.length > 0) {
          errors.push(`Missing required column(s): ${missing.join(", ")}`);
        }

        const parsedRows: BulkRow[] = results.data.map((r) => ({
          name: r.name?.trim() ?? "",
          category: r.category?.trim() ?? "",
          subcategory: r.subcategory?.trim() ?? "",
          sector: resolveSector(r.sector),
          description: r.description?.trim() ?? "",
          address: r.address?.trim() || undefined,
          landmark: r.landmark?.trim() || undefined,
          phone: r.phone?.trim() || undefined,
          whatsapp: r.whatsapp?.trim() || undefined,
          website: r.website?.trim() || undefined,
          instagram: r.instagram?.trim() || undefined,
          hours_text: r.hours_text?.trim() || undefined,
          price_range: r.price_range?.trim() || undefined,
          is_published: parseBool(r.is_published, true),
          featured: parseBool(r.featured, false),
        }));

        setRows(parsedRows);
        setParseErrors(errors);
      },
      error: (err) => {
        setParseErrors([`Couldn't read file: ${err.message}`]);
        setRows([]);
      },
    });
  }

  function handleUpload() {
    startTransition(async () => {
      const res = await bulkCreateListings(rows);
      setResult(res);
      if (res.errors.length === 0) {
        setRows([]);
        setFileName(null);
        if (fileInputRef.current) fileInputRef.current.value = "";
      }
    });
  }

  return (
    <div>
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold text-foreground">Bulk upload</h1>
        <Link href="/admin" className="text-sm font-medium text-foreground/60 hover:text-foreground">
          ← Back to listings
        </Link>
      </div>

      <div className="mt-6 max-w-2xl rounded-2xl border border-foreground/10 bg-foreground/[0.02] p-6">
        <p className="text-sm text-foreground/70">
          Upload a CSV of listings. Required columns:{" "}
          <code className="rounded bg-foreground/10 px-1.5 py-0.5 text-xs">
            {REQUIRED_COLUMNS.join(", ")}
          </code>
          . Sector must be a sector number configured in{" "}
          <Link href="/admin/sectors" className="font-semibold text-brand-dark hover:underline">
            Admin → Sectors
          </Link>
          {sectors.length > 0 && (
            <>
              {" "}
              (currently <strong>{sectors.map((s) => s.id).join(", ")}</strong>)
            </>
          )}
          . Need a new sector? Add it there first, then re-upload.
          <strong> category</strong> must match an existing top-level category
          (e.g. &quot;Food &amp; Dining&quot;) and <strong>subcategory</strong>{" "}
          must match one of its subcategories (e.g. &quot;Restaurants&quot;) —
          the pairing matters since some subcategory names (like
          &quot;Insurance&quot;) exist under more than one category.
        </p>
        <a
          href="/delhidwarka-bulk-template.csv"
          download
          className="mt-3 inline-block text-sm font-semibold text-brand-dark hover:underline"
        >
          Download CSV template ↓
        </a>
      </div>

      <div className="mt-6 max-w-2xl">
        <input
          ref={fileInputRef}
          type="file"
          accept=".csv,text/csv"
          onChange={(e) => {
            const file = e.target.files?.[0];
            if (file) handleFile(file);
          }}
          className="block w-full text-sm text-foreground/70 file:mr-4 file:rounded-full file:border-0 file:bg-brand file:px-4 file:py-2 file:text-sm file:font-semibold file:text-white hover:file:bg-brand-dark"
        />

        {parseErrors.length > 0 && (
          <div className="mt-4 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700 dark:bg-red-950/30 dark:text-red-400">
            {parseErrors.map((e) => (
              <p key={e}>{e}</p>
            ))}
          </div>
        )}

        {fileName && rows.length > 0 && parseErrors.length === 0 && (
          <div className="mt-6">
            <p className="text-sm font-medium text-foreground">
              {fileName}: {rows.length} row{rows.length === 1 ? "" : "s"} parsed.
            </p>

            <div className="mt-3 max-h-64 overflow-auto rounded-xl border border-foreground/10">
              <table className="w-full text-left text-xs">
                <thead className="sticky top-0 bg-foreground/[0.04] text-foreground/60">
                  <tr>
                    <th className="px-3 py-2 font-medium">Name</th>
                    <th className="px-3 py-2 font-medium">Category</th>
                    <th className="px-3 py-2 font-medium">Subcategory</th>
                    <th className="px-3 py-2 font-medium">Sector</th>
                  </tr>
                </thead>
                <tbody>
                  {rows.slice(0, 20).map((r, i) => (
                    <tr key={i} className="border-t border-foreground/5">
                      <td className="px-3 py-1.5 text-foreground/80">{r.name}</td>
                      <td className="px-3 py-1.5 text-foreground/60">{r.category}</td>
                      <td className="px-3 py-1.5 text-foreground/60">{r.subcategory}</td>
                      <td
                        className={
                          Number.isNaN(r.sector)
                            ? "px-3 py-1.5 font-medium text-red-600"
                            : "px-3 py-1.5 text-foreground/60"
                        }
                      >
                        {Number.isNaN(r.sector) ? "Unrecognized sector" : r.sector}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            {rows.length > 20 && (
              <p className="mt-1 text-xs text-foreground/50">
                +{rows.length - 20} more row{rows.length - 20 === 1 ? "" : "s"} not shown.
              </p>
            )}

            <button
              type="button"
              onClick={handleUpload}
              disabled={isPending}
              className="mt-4 rounded-full bg-brand px-6 py-2.5 text-sm font-semibold text-white transition-colors hover:bg-brand-dark disabled:opacity-60"
            >
              {isPending ? "Uploading…" : `Upload ${rows.length} listing${rows.length === 1 ? "" : "s"}`}
            </button>
          </div>
        )}

        {result && (
          <div className="mt-6 rounded-xl border border-foreground/10 bg-background p-5">
            <p className="text-sm font-semibold text-foreground">
              {result.inserted} listing{result.inserted === 1 ? "" : "s"} created.
            </p>
            {result.errors.length > 0 && (
              <div className="mt-3">
                <p className="text-sm font-medium text-red-600">
                  {result.errors.length} row{result.errors.length === 1 ? "" : "s"} skipped:
                </p>
                <ul className="mt-2 space-y-1 text-xs text-foreground/70">
                  {result.errors.map((e, i) => (
                    <li key={i}>
                      Row {e.row} ({e.name}): {e.message}
                    </li>
                  ))}
                </ul>
              </div>
            )}
            {result.inserted > 0 && (
              <Link href="/admin" className="mt-4 inline-block text-sm font-semibold text-brand-dark hover:underline">
                View listings →
              </Link>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

function parseBool(value: string | undefined, fallback: boolean): boolean {
  if (value === undefined || value === "") return fallback;
  return ["true", "1", "yes", "y"].includes(value.trim().toLowerCase());
}
